# Generated by Django 4.2.7 on 2024-06-01 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название отдела')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('vacation_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(52)], verbose_name='Количество отпускных дней')),
                ('is_working', models.BooleanField(default=True, verbose_name='Статус (работает)')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Руководитель')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departments', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('vacation_type', models.CharField(choices=[('paid', 'Оплачиваемый'), ('unpaid', 'Неоплачиваемый'), ('study', 'Учебный')], default='paid', max_length=10, verbose_name='Тип отпуска')),
                ('status', models.CharField(choices=[('approved', 'Одобрена'), ('pending', 'В рассмотрении'), ('rejected', 'Не одобрена')], default='pending', max_length=10, verbose_name='Статус заявки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
            },
        ),
    ]
