# Generated by Django 4.2.7 on 2024-06-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('vacation_type', models.CharField(choices=[('paid', 'Оплачиваемый'), ('unpaid', 'Неоплачиваемый'), ('study', 'Учебный')], default='paid', max_length=50, verbose_name='Тип отпуска')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заявление на отпуск',
                'verbose_name_plural': 'Заявления на отпуска',
            },
        ),
    ]
