# Generated by Django 4.2.7 on 2024-06-05 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_preholidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='used_up_days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(52)], verbose_name='Израсходовано дней'),
        ),
    ]
