# Generated by Django 4.2.7 on 2024-06-05 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employees_used_up_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала работы'),
        ),
    ]
