# Generated by Django 4.2.7 on 2024-06-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_сanceledholidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(default='pending', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
