# Generated by Django 4.2.7 on 2024-06-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vacation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='status',
        ),
    ]
