# Generated by Django 4.2.7 on 2024-06-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_vacation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacation_type',
            field=models.CharField(choices=[('paid', 'Оплачиваемый'), ('unpaid', 'Неоплачиваемый'), ('study', 'Учебный')], default='paid', max_length=50, verbose_name='Тип отпуска'),
        ),
    ]
