# Generated by Django 4.2.7 on 2024-06-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vacation_vacation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'verbose_name': 'Одобренный отпуск', 'verbose_name_plural': 'Одобренные отпуска'},
        ),
        migrations.AlterModelOptions(
            name='сanceledholidays',
            options={'verbose_name': 'Отклонённое заявление на отпуск', 'verbose_name_plural': 'Отклонённые заявления на отпуска'},
        ),
    ]
