from django.urls import path

from apps.leave.views import (
    schedule_draft,
    schedule_planning,
    schedule_reviews,
)


urlpatterns = [
    path("calendar/planning/", schedule_planning.schedule_planning_current, name="schedule_planning_current"),
    path("calendar/planning/<int:year>/", schedule_planning.schedule_planning, name="schedule_planning"),
    path(
        "calendar/planning/<int:year>/start-next/",
        schedule_planning.start_next_schedule_planning_cycle,
        name="schedule_planning_start_next",
    ),
    path(
        "calendar/planning/<int:year>/department-review/start/",
        schedule_reviews.start_schedule_department_review,
        name="schedule_department_review_start",
    ),
    path(
        "calendar/planning/<int:year>/department-review/<int:approval_id>/approve/",
        schedule_reviews.approve_schedule_department_review,
        name="schedule_department_review_approve",
    ),
    path(
        "calendar/planning/<int:year>/department-review/<int:approval_id>/return/",
        schedule_reviews.return_schedule_department_review,
        name="schedule_department_review_return",
    ),
    path(
        "calendar/planning/<int:year>/department-review/<int:approval_id>/rework/",
        schedule_reviews.schedule_department_review_rework,
        name="schedule_department_review_rework",
    ),
    path(
        "calendar/planning/<int:year>/department-review/<int:approval_id>/rework/resubmit/",
        schedule_reviews.resubmit_schedule_department_review,
        name="schedule_department_review_resubmit",
    ),
    path(
        "calendar/planning/<int:year>/department-review/<int:approval_id>/rework/<int:employee_id>/suggestions/",
        schedule_reviews.schedule_department_review_rework_suggestions,
        name="schedule_department_review_rework_suggestions",
    ),
    path(
        "calendar/planning/<int:year>/department-review/<int:approval_id>/rework/<int:employee_id>/preview-package/",
        schedule_reviews.schedule_department_review_rework_package_preview,
        name="schedule_department_review_rework_package_preview",
    ),
    path(
        "calendar/planning/<int:year>/department-review/<int:approval_id>/rework/<int:employee_id>/place/",
        schedule_reviews.schedule_department_review_rework_place,
        name="schedule_department_review_rework_place",
    ),
    path(
        "calendar/planning/<int:year>/final-review/submit/",
        schedule_reviews.submit_schedule_final_review,
        name="schedule_final_review_submit",
    ),
    path(
        "calendar/planning/<int:year>/final-review/<int:approval_id>/approve/",
        schedule_reviews.approve_schedule_final_review,
        name="schedule_final_review_approve",
    ),
    path(
        "calendar/planning/<int:year>/final-review/<int:approval_id>/return/",
        schedule_reviews.return_schedule_final_review,
        name="schedule_final_review_return",
    ),
    path(
        "calendar/planning/<int:year>/final-review/<int:approval_id>/departments/<int:department_id>/rework/",
        schedule_reviews.open_schedule_final_department_rework,
        name="schedule_final_review_open_department_rework",
    ),
    path("calendar/drafts/<int:year>/create/", schedule_draft.create_schedule_draft, name="schedule_draft_create"),
    path(
        "calendar/drafts/<int:year>/auto-place/",
        schedule_draft.auto_place_schedule_draft_remaining,
        name="schedule_draft_auto_place",
    ),
    path(
        "calendar/drafts/<int:year>/auto-place/jobs/<int:job_id>/status/",
        schedule_draft.auto_place_schedule_draft_status,
        name="schedule_draft_auto_place_status",
    ),
    path(
        "calendar/drafts/<int:year>/auto-place/preview/",
        schedule_draft.auto_place_schedule_draft_preview,
        name="schedule_draft_auto_place_preview",
    ),
    path(
        "calendar/drafts/<int:year>/employees/<int:employee_id>/day-calculation/",
        schedule_draft.schedule_draft_day_calculation,
        name="schedule_draft_day_calculation",
    ),
    path(
        "calendar/drafts/<int:year>/items/<int:item_id>/review/",
        schedule_draft.schedule_draft_item_review,
        name="schedule_draft_item_review",
    ),
    path(
        "calendar/drafts/<int:year>/manual-place/<int:employee_id>/preview/",
        schedule_draft.manual_schedule_draft_preview,
        name="schedule_draft_manual_preview",
    ),
    path(
        "calendar/drafts/<int:year>/manual-place/<int:employee_id>/preview-package/",
        schedule_draft.manual_schedule_draft_package_preview,
        name="schedule_draft_manual_package_preview",
    ),
    path(
        "calendar/drafts/<int:year>/manual-place/<int:employee_id>/suggestions/",
        schedule_draft.manual_schedule_draft_suggestions,
        name="schedule_draft_manual_suggestions",
    ),
    path(
        "calendar/drafts/<int:year>/manual-place/<int:employee_id>/",
        schedule_draft.manual_place_schedule_draft_item,
        name="schedule_draft_manual_place",
    ),
    path(
        "calendar/drafts/<int:year>/urgent-closures/<int:employee_id>/create/",
        schedule_draft.create_urgent_closure,
        name="urgent_closure_create",
    ),
    path(
        "calendar/drafts/<int:year>/urgent-closures/<int:employee_id>/preview/",
        schedule_draft.urgent_closure_preview,
        name="urgent_closure_preview",
    ),
    path(
        "calendar/drafts/<int:year>/urgent-closures/<int:employee_id>/options/",
        schedule_draft.urgent_closure_options,
        name="urgent_closure_options",
    ),
    path(
        "calendar/drafts/<int:year>/items/<int:item_id>/feedback/",
        schedule_draft.schedule_draft_candidate_feedback,
        name="schedule_draft_candidate_feedback",
    ),
    path("calendar/drafts/<int:year>/", schedule_draft.schedule_draft_detail, name="schedule_draft_detail"),
]
