# Generated by Django 5.0.6 on 2026-04-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_departments_options_alter_employees_options_and_more'),
        ('leave', '0002_relabel_content_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на отпуск', 'verbose_name_plural': 'Заявки на отпуск'},
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to='employees.employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='vacation_type',
            field=models.CharField(choices=[('paid', 'Оплачиваемый'), ('unpaid', 'Неоплачиваемый'), ('study', 'Учебный')], default='paid', max_length=50, verbose_name='Тип отпуска'),
        ),
    ]
