# Generated by Django 5.0.6 on 2026-04-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_clean_authorized_person_profile'),
        ('leave', '0003_alter_vacationrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStaffingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_staff_required', models.PositiveSmallIntegerField(default=1)),
                ('max_absent', models.PositiveSmallIntegerField(default=1)),
                ('criticality_level', models.PositiveSmallIntegerField(default=3)),
                ('substitution_group', models.CharField(blank=True, default='', max_length=120)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_rule', to='employees.departments')),
            ],
            options={
                'db_table': 'leave_departmentstaffingrule',
            },
        ),
        migrations.CreateModel(
            name='DepartmentWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('load_level', models.PositiveSmallIntegerField(default=3)),
                ('min_staff_required', models.PositiveSmallIntegerField(default=1)),
                ('max_absent', models.PositiveSmallIntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_months', to='employees.departments')),
            ],
            options={
                'db_table': 'leave_departmentworkload',
                'ordering': ['year', 'department_id', 'month'],
            },
        ),
        migrations.CreateModel(
            name='VacationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('primary', 'Основное'), ('backup', 'Запасное')], default='primary', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('filled', 'Заполнено'), ('skipped', 'Пропущено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_automatically', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_preferences', to='employees.employees')),
            ],
            options={
                'db_table': 'leave_vacationpreference',
                'ordering': ['year', 'employee_id', 'priority', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='VacationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Год')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('department_review', 'На согласовании'), ('approved', 'Утвержден'), ('archived', 'Архив')], default='draft', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vacation_schedules', to='employees.employees', verbose_name='Утвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacation_schedules', to='employees.employees', verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Годовой график отпусков',
                'verbose_name_plural': 'Годовые графики отпусков',
                'db_table': 'leave_vacationschedule',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='VacationScheduleAuthorizedApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_schedule_approvals', to='employees.employees')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_approvals', to='leave.vacationschedule')),
            ],
            options={
                'db_table': 'leave_vacationschedule_authorizedapproval',
            },
        ),
        migrations.CreateModel(
            name='VacationScheduleDepartmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_approvals', to='employees.departments')),
                ('department_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_schedule_approvals', to='employees.employees')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_approvals', to='leave.vacationschedule')),
            ],
            options={
                'db_table': 'leave_vacationschedule_departmentapproval',
            },
        ),
        migrations.CreateModel(
            name='VacationScheduleEnterpriseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('enterprise_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_schedule_approvals', to='employees.employees')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_approvals', to='leave.vacationschedule')),
            ],
            options={
                'db_table': 'leave_vacationschedule_enterpriseapproval',
            },
        ),
        migrations.CreateModel(
            name='VacationScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('vacation_type', models.CharField(choices=[('paid', 'Оплачиваемый'), ('unpaid', 'Неоплачиваемый'), ('study', 'Учебный')], default='paid', max_length=50, verbose_name='Тип отпуска')),
                ('chargeable_days', models.PositiveIntegerField(default=0, verbose_name='Списываемые дни')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланирован'), ('approved', 'Утвержден'), ('transferred', 'Перенесен'), ('cancelled', 'Отменен')], default='draft', max_length=32, verbose_name='Статус')),
                ('source', models.CharField(choices=[('generated', 'Сформирован системой'), ('manual', 'Внесен вручную'), ('transfer', 'Создан переносом')], default='generated', max_length=32, verbose_name='Источник')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка риска')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=16, verbose_name='Уровень риска')),
                ('generated_by_ai', models.BooleanField(default=False, verbose_name='Сформировано ИИ')),
                ('was_changed_by_manager', models.BooleanField(default=False, verbose_name='Изменено руководителем')),
                ('manager_comment', models.TextField(blank=True, default='', verbose_name='Комментарий руководителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_schedule_items', to='employees.employees', verbose_name='Сотрудник')),
                ('previous_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_items', to='leave.vacationscheduleitem', verbose_name='Предыдущий пункт графика')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leave.vacationschedule', verbose_name='График')),
            ],
            options={
                'verbose_name': 'Пункт графика отпусков',
                'verbose_name_plural': 'Пункты графика отпусков',
                'db_table': 'leave_vacationscheduleitem',
                'ordering': ['start_date', 'employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='VacationScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_start_date', models.DateField()),
                ('old_end_date', models.DateField()),
                ('new_start_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=16)),
                ('department_load_level', models.PositiveSmallIntegerField(default=1)),
                ('overlapping_absences_count', models.PositiveSmallIntegerField(default=0)),
                ('remaining_staff_count', models.PositiveSmallIntegerField(default=0)),
                ('min_staff_required', models.PositiveSmallIntegerField(default=0)),
                ('balance_after_change', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_schedule_change_requests', to='employees.employees')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_vacation_schedule_changes', to='employees.employees')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vacation_schedule_changes', to='employees.employees')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='leave.vacationscheduleitem')),
            ],
            options={
                'db_table': 'leave_vacationschedule_changerequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='departmentworkload',
            constraint=models.UniqueConstraint(fields=('department', 'year', 'month'), name='unique_department_workload_month'),
        ),
        migrations.AddIndex(
            model_name='vacationpreference',
            index=models.Index(fields=['employee', 'year'], name='leave_vacat_employe_f21137_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacationscheduleauthorizedapproval',
            constraint=models.UniqueConstraint(fields=('schedule',), name='unique_schedule_authorized_approval'),
        ),
        migrations.AddConstraint(
            model_name='vacationscheduledepartmentapproval',
            constraint=models.UniqueConstraint(fields=('schedule', 'department'), name='unique_schedule_department_approval'),
        ),
        migrations.AddConstraint(
            model_name='vacationscheduleenterpriseapproval',
            constraint=models.UniqueConstraint(fields=('schedule',), name='unique_schedule_enterprise_approval'),
        ),
        migrations.AddIndex(
            model_name='vacationscheduleitem',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='leave_vacat_employe_0fffed_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationscheduleitem',
            index=models.Index(fields=['schedule', 'status'], name='leave_vacat_schedul_0471c9_idx'),
        ),
    ]
