# Generated by Django 5.0.6 on 2026-04-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_clean_authorized_person_profile'),
        ('leave', '0004_departmentstaffingrule_departmentworkload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='balance_after_request',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баланс после заявки'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='department_load_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Нагрузка отдела'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='min_staff_required',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Минимум сотрудников'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='overlapping_absences_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Пересечения отсутствий'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='remaining_staff_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Останется сотрудников'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий согласующего'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vacation_requests', to='employees.employees', verbose_name='Рассмотрел'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=16, verbose_name='Уровень риска'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Оценка риска'),
        ),
    ]
