# Generated by Django 5.0.6 on 2026-04-25 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_clean_authorized_person_profile'),
        ('leave', '0005_vacationrequest_balance_after_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationEntitlementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_year_number', models.PositiveIntegerField(verbose_name='Номер рабочего года')),
                ('period_start', models.DateField(verbose_name='Начало рабочего года')),
                ('period_end', models.DateField(verbose_name='Окончание рабочего года')),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Право на отпуск')),
                ('available_from', models.DateField(verbose_name='Доступно с')),
                ('must_use_by', models.DateField(verbose_name='Использовать до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_entitlement_periods', to='employees.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Рабочий год для отпуска',
                'verbose_name_plural': 'Рабочие годы для отпусков',
                'db_table': 'leave_vacationentitlementperiod',
                'ordering': ['employee_id', 'period_start'],
            },
        ),
        migrations.CreateModel(
            name='VacationEntitlementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('request', 'Заявка'), ('schedule', 'Годовой график')], max_length=16, verbose_name='Источник')),
                ('state', models.CharField(choices=[('used', 'Использовано'), ('reserved', 'В резерве')], max_length=16, verbose_name='Состояние')),
                ('allocated_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Распределено дней')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_entitlement_allocations', to='employees.employees', verbose_name='Сотрудник')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_allocations', to='leave.vacationscheduleitem', verbose_name='Пункт графика')),
                ('vacation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_allocations', to='leave.vacationrequest', verbose_name='Заявка')),
                ('entitlement_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='leave.vacationentitlementperiod', verbose_name='Рабочий год')),
            ],
            options={
                'verbose_name': 'Распределение отпускных дней',
                'verbose_name_plural': 'Распределения отпускных дней',
                'db_table': 'leave_vacationentitlementallocation',
                'ordering': ['employee_id', 'entitlement_period__period_start', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vacationentitlementperiod',
            index=models.Index(fields=['employee', 'period_start', 'period_end'], name='leave_vacat_employe_887969_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationentitlementperiod',
            index=models.Index(fields=['employee', 'available_from'], name='leave_vacat_employe_4b4e6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacationentitlementperiod',
            constraint=models.UniqueConstraint(fields=('employee', 'working_year_number'), name='unique_employee_working_year'),
        ),
        migrations.AddConstraint(
            model_name='vacationentitlementperiod',
            constraint=models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='unique_employee_working_period'),
        ),
        migrations.AddIndex(
            model_name='vacationentitlementallocation',
            index=models.Index(fields=['employee', 'state'], name='leave_vacat_employe_7c4dec_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationentitlementallocation',
            index=models.Index(fields=['source_kind', 'state'], name='leave_vacat_source__132bac_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacationentitlementallocation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('schedule_item__isnull', True), ('vacation_request__isnull', False)), models.Q(('schedule_item__isnull', False), ('vacation_request__isnull', True)), _connector='OR'), name='entitlement_allocation_single_source'),
        ),
        migrations.AddConstraint(
            model_name='vacationentitlementallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('vacation_request__isnull', False)), fields=('entitlement_period', 'vacation_request'), name='unique_entitlement_request_alloc'),
        ),
        migrations.AddConstraint(
            model_name='vacationentitlementallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_item__isnull', False)), fields=('entitlement_period', 'schedule_item'), name='unique_entitlement_schedule_alloc'),
        ),
    ]
