# Generated by Django 5.0.6 on 2026-04-26 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0006_vacationentitlementperiod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationscheduleitem",
            name="created_from_change_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_schedule_items",
                to="leave.vacationschedulechangerequest",
                verbose_name="Создан из запроса переноса",
            ),
        ),
    ]
