# Generated by Django 5.0.6 on 2026-04-28 23:59

import django.db.models.deletion
import django.utils.timezone
from datetime import timedelta
from django.db import migrations, models


def get_submitted_at(created_at, reviewed_at=None):
    submitted_at = created_at + timedelta(minutes=30)
    if reviewed_at is not None and submitted_at >= reviewed_at:
        submitted_at = created_at + ((reviewed_at - created_at) / 2)
    return submitted_at


def backfill_vacation_request_history(apps, schema_editor):
    VacationRequest = apps.get_model('leave', 'VacationRequest')
    VacationRequestHistory = apps.get_model('leave', 'VacationRequestHistory')

    history_entries = []
    for vacation in VacationRequest.objects.select_related('employee', 'reviewed_by').iterator():
        created_at = vacation.created_at or django.utils.timezone.now()
        reviewed_at = vacation.reviewed_at
        if vacation.status in {'approved', 'rejected'} and reviewed_at and reviewed_at < created_at:
            created_at = reviewed_at - timedelta(days=2)
        submitted_at = get_submitted_at(created_at, reviewed_at)
        history_entries.extend(
            [
                VacationRequestHistory(
                    vacation_request_id=vacation.id,
                    employee_id=vacation.employee_id,
                    actor_id=vacation.employee_id,
                    action='created',
                    title='Заявка создана',
                    description='Сотрудник сформировал заявку на отпуск.',
                    status_snapshot='pending',
                    created_at=created_at,
                ),
                VacationRequestHistory(
                    vacation_request_id=vacation.id,
                    employee_id=vacation.employee_id,
                    actor_id=vacation.employee_id,
                    action='submitted',
                    title='Отправлена на согласование',
                    description='Система направила заявку по маршруту согласования.',
                    status_snapshot='pending',
                    created_at=submitted_at,
                ),
            ]
        )
        if vacation.status in {'approved', 'rejected'} and reviewed_at:
            is_approved = vacation.status == 'approved'
            history_entries.append(
                VacationRequestHistory(
                    vacation_request_id=vacation.id,
                    employee_id=vacation.employee_id,
                    actor_id=vacation.reviewed_by_id,
                    action='approved' if is_approved else 'rejected',
                    title='Заявка одобрена' if is_approved else 'Заявка отклонена',
                    description='Согласующий принял решение по заявке.',
                    status_snapshot=vacation.status,
                    created_at=reviewed_at,
                )
            )

    VacationRequestHistory.objects.bulk_create(history_entries, batch_size=1000)


def remove_backfilled_vacation_request_history(apps, schema_editor):
    VacationRequestHistory = apps.get_model('leave', 'VacationRequestHistory')
    VacationRequestHistory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employees_is_working_and_more'),
        ('leave', '0010_harden_leave_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('submitted', 'Отправлена на согласование'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('deleted', 'Удалена')], max_length=32, verbose_name='Действие')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('status_snapshot', models.CharField(blank=True, default='', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата действия')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_request_history_actions', to='employees.employees', verbose_name='Инициатор')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_request_history', to='employees.employees', verbose_name='Сотрудник')),
                ('vacation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='leave.vacationrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История заявки на отпуск',
                'verbose_name_plural': 'История заявок на отпуск',
                'db_table': 'leave_vacationrequesthistory',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['vacation_request', 'created_at'], name='leave_vacat_vacatio_57caa3_idx'), models.Index(fields=['employee', 'created_at'], name='leave_vacat_employe_f074ab_idx'), models.Index(fields=['action', 'created_at'], name='leave_vacat_action_6d6f83_idx')],
            },
        ),
        migrations.RunPython(
            backfill_vacation_request_history,
            remove_backfilled_vacation_request_history,
        ),
    ]
