# Generated by Django 5.0.6 on 2026-05-09 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_substitution_rule_capacity'),
        ('leave', '0012_vacationpreferencecollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationUrgentClosureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_year', models.PositiveIntegerField(verbose_name='Год черновика')),
                ('closure_year', models.PositiveIntegerField(verbose_name='Год закрытия остатка')),
                ('required_days', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Нужно закрыть дней')),
                ('deadline', models.DateField(verbose_name='Использовать до')),
                ('proposed_start_date', models.DateField(verbose_name='Предложенная дата начала')),
                ('proposed_end_date', models.DateField(verbose_name='Предложенная дата окончания')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Комментарий HR')),
                ('status', models.CharField(choices=[('department_review', 'У руководителя отдела'), ('employee_review', 'У сотрудника'), ('hr_finalization', 'Финализация HR'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='department_review', max_length=32, verbose_name='Статус')),
                ('department_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения руководителя')),
                ('department_comment', models.TextField(blank=True, default='', verbose_name='Комментарий руководителя')),
                ('employee_responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа сотрудника')),
                ('employee_comment', models.TextField(blank=True, default='', verbose_name='Комментарий сотрудника')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата финализации')),
                ('final_comment', models.TextField(blank=True, default='', verbose_name='Комментарий финализации')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения')),
                ('rejection_comment', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка риска')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=16, verbose_name='Уровень риска')),
                ('department_load_level', models.PositiveSmallIntegerField(default=1, verbose_name='Нагрузка отдела')),
                ('overlapping_absences_count', models.PositiveSmallIntegerField(default=0, verbose_name='Пересечения отсутствий')),
                ('remaining_staff_count', models.PositiveSmallIntegerField(default=0, verbose_name='Останется сотрудников')),
                ('min_staff_required', models.PositiveSmallIntegerField(default=0, verbose_name='Минимум сотрудников')),
                ('balance_after_closure', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баланс после закрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_urgent_closure_requests', to='employees.employees', verbose_name='Создал')),
                ('created_schedule_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgent_closure_request', to='leave.vacationscheduleitem', verbose_name='Созданный пункт графика')),
                ('department_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reviewed_urgent_closures', to='employees.employees', verbose_name='Рассмотрел руководитель отдела')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_closure_requests', to='employees.employees', verbose_name='Сотрудник')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_urgent_closure_requests', to='employees.employees', verbose_name='Финализировал HR')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_urgent_closure_requests', to='employees.employees', verbose_name='Отклонил')),
            ],
            options={
                'verbose_name': 'Закрытие срочного остатка',
                'verbose_name_plural': 'Закрытия срочных остатков',
                'db_table': 'leave_vacationurgentclosurerequest',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['employee', 'planning_year', 'status'], name='urgent_close_emp_plan_idx'), models.Index(fields=['status', '-created_at'], name='urgent_close_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vacationurgentclosurerequest',
            constraint=models.CheckConstraint(check=models.Q(('proposed_start_date__lte', models.F('proposed_end_date'))), name='urgent_closure_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='vacationurgentclosurerequest',
            constraint=models.CheckConstraint(check=models.Q(('required_days__gt', 0)), name='urgent_closure_required_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='vacationurgentclosurerequest',
            constraint=models.CheckConstraint(check=models.Q(('department_load_level__gte', 1), ('department_load_level__lte', 5)), name='urgent_closure_department_load_1_5'),
        ),
        migrations.AddConstraint(
            model_name='vacationurgentclosurerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('department_review', 'employee_review', 'hr_finalization'))), fields=('employee', 'planning_year', 'deadline'), name='unique_active_urgent_closure'),
        ),
    ]
