# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0015_alter_vacationpreference_remainder_policy_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacationpreference",
            name="remainder_policy",
            field=models.CharField(
                choices=[
                    ("auto", "Можно распределить автоматически"),
                    ("approval", "Сначала согласовать со мной"),
                    ("defer", "Не планировать сверх указанного периода"),
                ],
                default="auto",
                max_length=24,
                verbose_name="Решение по остатку",
            ),
        ),
    ]
