# Generated by Django 5.0.6 on 2026-05-10 00:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_substitution_rule_capacity'),
        ('leave', '0016_restore_vacationpreference_auto_remainder_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationscheduleitem',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уверенность ИИ'),
        ),
        migrations.AddField(
            model_name='vacationscheduleitem',
            name='ai_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Пояснение ИИ'),
        ),
        migrations.AddField(
            model_name='vacationscheduleitem',
            name='ai_model_version',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Версия ИИ-модели'),
        ),
        migrations.AddField(
            model_name='vacationscheduleitem',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Оценка ИИ'),
        ),
        migrations.CreateModel(
            name='VacationScheduleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('vacation_type', models.CharField(choices=[('paid', 'Оплачиваемый'), ('unpaid', 'Неоплачиваемый'), ('study', 'Учебный')], default='paid', max_length=50, verbose_name='Тип отпуска')),
                ('chargeable_days', models.PositiveIntegerField(default=0, verbose_name='Списываемые дни')),
                ('kind', models.CharField(choices=[('primary_preference', 'Основное пожелание'), ('backup_preference', 'Запасное пожелание'), ('auto', 'Автоподбор'), ('auto_urgent', 'Срочный остаток'), ('auto_topup', 'Продление отпуска'), ('manual', 'Ручная проверка')], default='auto', max_length=32, verbose_name='Тип кандидата')),
                ('source', models.CharField(choices=[('generated', 'Сформирован системой'), ('manual', 'Внесен вручную'), ('transfer', 'Создан переносом')], default='generated', max_length=32, verbose_name='Источник')),
                ('passed_hard_rules', models.BooleanField(default=False, verbose_name='Прошел жесткие правила')),
                ('block_reason_key', models.CharField(blank=True, default='', max_length=80, verbose_name='Код блокировки')),
                ('block_reason', models.TextField(blank=True, default='', verbose_name='Причина блокировки')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка риска')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=16, verbose_name='Уровень риска')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Признаки модели')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Оценка')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уверенность')),
                ('model_version', models.CharField(blank=True, default='', max_length=80, verbose_name='Версия модели')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Пояснение выбора')),
                ('decision', models.CharField(choices=[('pending', 'Не выбран'), ('selected', 'Выбран'), ('rejected', 'Отклонен'), ('blocked', 'Заблокирован правилами')], default='pending', max_length=24, verbose_name='Решение')),
                ('decision_rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место в рейтинге')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_schedule_candidates', to='employees.employees', verbose_name='Сотрудник')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_candidates', to='leave.vacationschedule', verbose_name='График')),
            ],
            options={
                'verbose_name': 'Кандидат периода графика',
                'verbose_name_plural': 'Кандидаты периодов графика',
                'db_table': 'leave_vacationschedule_candidate',
                'ordering': ['generation_run_id', 'employee__last_name', 'decision_rank', '-score', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='vacationscheduleitem',
            name='selected_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_schedule_items', to='leave.vacationschedulecandidate', verbose_name='Выбранный кандидат'),
        ),
        migrations.CreateModel(
            name='VacationScheduleGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('mode', models.CharField(choices=[('rules', 'Правила'), ('neural', 'Нейромодуль'), ('hybrid', 'Гибридный режим')], default='rules', max_length=24, verbose_name='Режим')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('running', 'Выполняется'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='created', max_length=24, verbose_name='Статус')),
                ('model_version', models.CharField(blank=True, default='', max_length=80, verbose_name='Версия модели')),
                ('candidates_count', models.PositiveIntegerField(default=0, verbose_name='Кандидатов')),
                ('selected_count', models.PositiveIntegerField(default=0, verbose_name='Выбрано')),
                ('rejected_count', models.PositiveIntegerField(default=0, verbose_name='Отклонено')),
                ('manual_count', models.PositiveIntegerField(default=0, verbose_name='Осталось вручную')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Средняя оценка')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запуска')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_schedule_generation_runs', to='employees.employees', verbose_name='Запустил')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='leave.vacationschedule', verbose_name='График')),
            ],
            options={
                'verbose_name': 'Запуск формирования графика',
                'verbose_name_plural': 'Запуски формирования графика',
                'db_table': 'leave_vacationschedule_generationrun',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='vacationschedulecandidate',
            name='generation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='leave.vacationschedulegenerationrun', verbose_name='Запуск генерации'),
        ),
        migrations.AddField(
            model_name='vacationscheduleitem',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_items', to='leave.vacationschedulegenerationrun', verbose_name='Запуск генерации'),
        ),
        migrations.AddConstraint(
            model_name='vacationscheduleitem',
            constraint=models.CheckConstraint(check=models.Q(('ai_score__isnull', True), models.Q(('ai_score__gte', 0), ('ai_score__lte', 100)), _connector='OR'), name='schedule_item_ai_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='vacationscheduleitem',
            constraint=models.CheckConstraint(check=models.Q(('ai_confidence__isnull', True), models.Q(('ai_confidence__gte', 0), ('ai_confidence__lte', 100)), _connector='OR'), name='schedule_item_ai_confidence_0_100'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulegenerationrun',
            index=models.Index(fields=['schedule', 'status'], name='leave_vacat_schedul_7357c6_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulegenerationrun',
            index=models.Index(fields=['year', 'mode', 'status'], name='leave_vacat_year_b701c9_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulegenerationrun',
            index=models.Index(fields=['started_at'], name='leave_vacat_started_978d80_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulegenerationrun',
            constraint=models.CheckConstraint(check=models.Q(('average_score__isnull', True), models.Q(('average_score__gte', 0), ('average_score__lte', 100)), _connector='OR'), name='generation_run_avg_score_0_100'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidate',
            index=models.Index(fields=['generation_run', 'employee'], name='leave_vacat_generat_aad3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidate',
            index=models.Index(fields=['schedule', 'decision'], name='leave_vacat_schedul_103769_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidate',
            index=models.Index(fields=['kind', 'passed_hard_rules'], name='leave_vacat_kind_3baa45_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidate',
            index=models.Index(fields=['decision', 'decision_rank'], name='leave_vacat_decisio_5a1452_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_date__isnull', True), ('start_date__isnull', True)), models.Q(('end_date__isnull', False), ('start_date__isnull', False), ('start_date__lte', models.F('end_date'))), _connector='OR'), name='schedule_candidate_date_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidate',
            constraint=models.CheckConstraint(check=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='schedule_candidate_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidate',
            constraint=models.CheckConstraint(check=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 100)), _connector='OR'), name='schedule_candidate_confidence_0_100'),
        ),
    ]
