# Generated by Django 5.0.6 on 2026-05-10 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_substitution_rule_capacity'),
        ('leave', '0017_vacationscheduleitem_ai_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationScheduleCandidateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('hr', 'HR'), ('department_head', 'Руководитель отдела'), ('enterprise_head', 'Руководитель предприятия')], max_length=32, verbose_name='Роль проверяющего')),
                ('decision', models.CharField(choices=[('agree', 'Согласен'), ('needs_change', 'Нужна правка'), ('reject', 'Отклонить')], max_length=32, verbose_name='Решение')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('score_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Оценка на момент отзыва')),
                ('confidence_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уверенность на момент отзыва')),
                ('model_version_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='Версия модели на момент отзыва')),
                ('explanation_snapshot', models.TextField(blank=True, default='', verbose_name='Пояснение на момент отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='leave.vacationschedulecandidate', verbose_name='Выбранный кандидат')),
                ('generation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='leave.vacationschedulegenerationrun', verbose_name='Запуск генерации')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_schedule_candidate_feedback', to='employees.employees', verbose_name='Проверяющий')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_feedback_entries', to='leave.vacationscheduleitem', verbose_name='Пункт черновика')),
            ],
            options={
                'verbose_name': 'Отзыв по кандидату графика',
                'verbose_name_plural': 'Отзывы по кандидатам графика',
                'db_table': 'leave_vacationschedule_candidatefeedback',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['schedule_item', 'decision'], name='leave_vacat_schedul_aaeb45_idx'), models.Index(fields=['candidate', 'decision'], name='leave_vacat_candida_ffc65f_idx'), models.Index(fields=['generation_run', 'decision'], name='leave_vacat_generat_60b648_idx'), models.Index(fields=['reviewer', 'updated_at'], name='leave_vacat_reviewe_540374_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidatefeedback',
            constraint=models.UniqueConstraint(fields=('schedule_item', 'reviewer'), name='unique_schedule_candidate_feedback_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidatefeedback',
            constraint=models.CheckConstraint(check=models.Q(('score_snapshot__isnull', True), models.Q(('score_snapshot__gte', 0), ('score_snapshot__lte', 100)), _connector='OR'), name='candidate_feedback_score_snapshot_0_100'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidatefeedback',
            constraint=models.CheckConstraint(check=models.Q(('confidence_snapshot__isnull', True), models.Q(('confidence_snapshot__gte', 0), ('confidence_snapshot__lte', 100)), _connector='OR'), name='candidate_feedback_conf_snapshot_0_100'),
        ),
    ]
