# Generated by Django 5.0.6 on 2026-05-11 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_substitution_rule_capacity'),
        ('leave', '0018_vacationschedulecandidatefeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationScheduleCandidatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_count', models.PositiveSmallIntegerField(default=1, verbose_name='Периодов')),
                ('total_chargeable_days', models.PositiveIntegerField(default=0, verbose_name='Всего списываемых дней')),
                ('source', models.CharField(choices=[('generated', 'Сформирован системой'), ('manual', 'Внесен вручную'), ('transfer', 'Создан переносом')], default='generated', max_length=32, verbose_name='Источник')),
                ('passed_hard_rules', models.BooleanField(default=False, verbose_name='Прошел жесткие правила')),
                ('block_reason_key', models.CharField(blank=True, default='', max_length=80, verbose_name='Код блокировки')),
                ('block_reason', models.TextField(blank=True, default='', verbose_name='Причина блокировки')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка риска')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=16, verbose_name='Уровень риска')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Признаки пакета')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Оценка')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уверенность')),
                ('model_version', models.CharField(blank=True, default='', max_length=80, verbose_name='Версия модели')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Пояснение выбора')),
                ('decision', models.CharField(choices=[('pending', 'Не выбран'), ('selected', 'Выбран'), ('rejected', 'Отклонен'), ('blocked', 'Заблокирован правилами')], default='pending', max_length=24, verbose_name='Решение')),
                ('decision_rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место в рейтинге')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_schedule_candidate_packages', to='employees.employees', verbose_name='Сотрудник')),
                ('generation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_packages', to='leave.vacationschedulegenerationrun', verbose_name='Запуск генерации')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_packages', to='leave.vacationschedule', verbose_name='График')),
            ],
            options={
                'verbose_name': 'Пакет кандидатов графика',
                'verbose_name_plural': 'Пакеты кандидатов графика',
                'db_table': 'leave_vacationschedule_candidatepackage',
                'ordering': ['generation_run_id', 'employee__last_name', 'decision_rank', '-score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VacationScheduleCandidatePackagePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('chargeable_days', models.PositiveIntegerField(default=0, verbose_name='Списываемые дни')),
                ('passed_hard_rules', models.BooleanField(default=False, verbose_name='Прошел жесткие правила')),
                ('block_reason_key', models.CharField(blank=True, default='', max_length=80, verbose_name='Код блокировки')),
                ('block_reason', models.TextField(blank=True, default='', verbose_name='Причина блокировки')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка риска')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=16, verbose_name='Уровень риска')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Признаки периода')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_periods', to='leave.vacationschedulecandidate', verbose_name='Кандидат периода')),
                ('candidate_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='leave.vacationschedulecandidatepackage', verbose_name='Пакет кандидатов')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_package_periods', to='leave.vacationscheduleitem', verbose_name='Пункт черновика')),
            ],
            options={
                'verbose_name': 'Период пакета кандидатов',
                'verbose_name_plural': 'Периоды пакетов кандидатов',
                'db_table': 'leave_vacationschedule_candidatepackage_period',
                'ordering': ['candidate_package_id', 'order', 'start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidatepackage',
            index=models.Index(fields=['generation_run', 'employee'], name='leave_vacat_generat_a0f057_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidatepackage',
            index=models.Index(fields=['schedule', 'decision'], name='leave_vacat_schedul_e73b58_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidatepackage',
            index=models.Index(fields=['decision', 'decision_rank'], name='leave_vacat_decisio_181eaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidatepackage',
            constraint=models.CheckConstraint(check=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='schedule_candidate_package_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidatepackage',
            constraint=models.CheckConstraint(check=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 100)), _connector='OR'), name='schedule_candidate_package_conf_0_100'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidatepackageperiod',
            index=models.Index(fields=['candidate_package', 'order'], name='leave_vacat_candida_361e13_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationschedulecandidatepackageperiod',
            index=models.Index(fields=['schedule_item'], name='leave_vacat_schedul_ebb5a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacationschedulecandidatepackageperiod',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='schedule_candidate_package_period_valid'),
        ),
    ]
