# Generated by Django 5.0.6 on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_substitution_rule_capacity"),
        ("leave", "0019_vacationschedulecandidatepackage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationschedule",
            name="manual_suggestion_cache_rebuilt_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Кэш ручных предложений пересобран"),
        ),
        migrations.AddField(
            model_name="vacationschedule",
            name="manual_suggestion_cache_version",
            field=models.PositiveIntegerField(default=0, verbose_name="Версия кэша ручных предложений"),
        ),
        migrations.CreateModel(
            name="VacationScheduleManualSuggestionCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField(default=0, verbose_name="Версия")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Данные предложений")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacation_schedule_manual_suggestion_caches",
                        to="employees.employees",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_suggestion_caches",
                        to="leave.vacationschedule",
                        verbose_name="График",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кэш ручных предложений графика",
                "verbose_name_plural": "Кэши ручных предложений графика",
                "db_table": "leave_vacationschedule_manualsuggestioncache",
                "ordering": ["schedule_id", "employee__last_name", "employee__first_name", "employee_id"],
            },
        ),
        migrations.AddIndex(
            model_name="vacationschedulemanualsuggestioncache",
            index=models.Index(fields=["schedule", "version"], name="leave_vacat_schedul_a85c11_idx"),
        ),
        migrations.AddIndex(
            model_name="vacationschedulemanualsuggestioncache",
            index=models.Index(fields=["employee", "version"], name="leave_vacat_employe_9b5618_idx"),
        ),
        migrations.AddConstraint(
            model_name="vacationschedulemanualsuggestioncache",
            constraint=models.UniqueConstraint(
                fields=("schedule", "employee"),
                name="unique_manual_suggestion_cache_employee",
            ),
        ),
    ]
