from decimal import Decimal

from apps.leave.models import VacationRequest, VacationSchedule
from apps.leave.ml.scoring import ACTIVE_CANDIDATE_SCORER_VERSION


AUTO_DRAFT_FALLBACK_CHUNK_DAYS = 28
AUTO_DRAFT_FALLBACK_STEPS = (52, 42, 35, 31, 28, 24, 21, 18, 14, 10, 7)
AUTO_DRAFT_ANCHOR_DAYS = (1, 4, 8, 11, 15, 18, 22, 25, 28)
AUTO_DRAFT_DENSE_WINDOW_DAYS = 75
AUTO_DRAFT_LOCAL_SEARCH_OFFSETS = (-7, -5, -3, -2, -1, 1, 2, 3, 5, 7)
AUTO_DRAFT_LOCAL_SEARCH_TOP_CANDIDATES = 8
AUTO_DRAFT_LOCAL_SEARCH_MAX_NEW_CANDIDATES = 24
AUTO_DRAFT_MAX_CHUNKS_PER_EMPLOYEE = 6
AUTO_DRAFT_MAX_AUTO_PLACE_PASSES = 8
AUTO_DRAFT_MIN_GAP_BETWEEN_ITEMS_DAYS = 14
AUTO_DRAFT_MAX_CANDIDATES_PER_STRATEGY = 16
AUTO_DRAFT_MAX_CANDIDATES_PER_EMPLOYEE = 48
AUTO_DRAFT_MAX_PACKAGE_SUGGESTIONS = 32
AUTO_DRAFT_PREVIEW_PACKAGE_SUGGESTIONS = 1
AUTO_DRAFT_PERSISTED_PACKAGE_ALTERNATIVES = 10
MANUAL_DRAFT_MAX_PACKAGE_PERIODS = 3
MANUAL_DRAFT_MAX_PACKAGE_SUGGESTIONS = 48
MANUAL_DRAFT_VISIBLE_PACKAGE_SUGGESTIONS = 18
MANUAL_DRAFT_SUGGESTION_CACHE_SCHEMA_VERSION = 3
DRAFT_GENERATION_RULES_MODEL_VERSION = "rules-v1"
DRAFT_GENERATION_HYBRID_MODEL_VERSION = ACTIVE_CANDIDATE_SCORER_VERSION
DRAFT_CANDIDATE_FEATURE_SCHEMA_VERSION = 1
PRIMARY_PREFERENCE_SCORE_TOLERANCE = Decimal("5.00")
PRIMARY_PREFERENCE_MIN_SCORE = Decimal("70.00")

DRAFT_CANDIDATE_PRIMARY_PREFERENCE = "primary_preference"
DRAFT_CANDIDATE_BACKUP_PREFERENCE = "backup_preference"
DRAFT_CANDIDATE_AUTO = "auto"
DRAFT_CANDIDATE_AUTO_URGENT = "auto_urgent"
DRAFT_CANDIDATE_AUTO_TOPUP = "auto_topup"

RISK_LEVEL_FEATURE_WEIGHT = {
    VacationRequest.RISK_LOW: 1,
    VacationRequest.RISK_MEDIUM: 2,
    VacationRequest.RISK_HIGH: 3,
}
EMPLOYEE_ROLE_FEATURE_WEIGHT = {
    "employee": 1,
    "hr": 2,
    "department_head": 3,
    "enterprise_head": 4,
    "authorized_person": 0,
}
SUMMER_VACATION_MONTHS = {6, 7, 8}
DRAFT_VIEW_SCHEDULE_STATUSES = (
    VacationSchedule.STATUS_DRAFT,
    VacationSchedule.STATUS_DEPARTMENT_REVIEW,
    VacationSchedule.STATUS_APPROVED,
)
