# Generated by Django 5.0.6 on 2026-04-22 12:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'РћС‚РґРµР»', 'verbose_name_plural': 'РћС‚РґРµР»С‹'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'РЎРѕС‚СЂСѓРґРЅРёРє', 'verbose_name_plural': 'РЎРѕС‚СЂСѓРґРЅРёРєРё'},
        ),
        migrations.AlterField(
            model_name='departments',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Р”Р°С‚Р° РґРѕР±Р°РІР»РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='РќР°Р·РІР°РЅРёРµ РѕС‚РґРµР»Р°'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Р”Р°С‚Р° РЅР°С‡Р°Р»Р° СЂР°Р±РѕС‚С‹'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.departments', verbose_name='РћС‚РґРµР»'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Р\xa0СѓРєРѕРІРѕРґРёС‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Р\xa0Р°Р±РѕС‚Р°РµС‚'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='login',
            field=models.CharField(max_length=150, unique=True, verbose_name='Р›РѕРіРёРЅ'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Р¤Р\x98Рћ'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='РЎР»СѓР¶РµР±РЅС‹Р№ РїР°СЂРѕР»СЊ (legacy)'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Р”РѕР»Р¶РЅРѕСЃС‚СЊ'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='used_up_days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(52)], verbose_name='Р\x98СЃРїРѕР»СЊР·РѕРІР°РЅРЅС‹Рµ РґРЅРё'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='vacation_days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(52)], verbose_name='РљРѕР»РёС‡РµСЃС‚РІРѕ РѕС‚РїСѓСЃРєРЅС‹С… РґРЅРµР№'),
        ),
    ]
