# Generated by Django 5.0.6 on 2026-04-22 19:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_split_employee_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='departments',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.departments', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='login',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Служебный пароль (legacy)'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='used_up_days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(52)], verbose_name='Использованные дни'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='vacation_days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(52)], verbose_name='Количество отпускных дней'),
        ),
    ]
