# Generated by Django 5.0.6 on 2026-04-23 11:17

from datetime import timedelta

import holidays
import django.core.validators
from django.db import migrations, models


def recalculate_leave_balances(apps, schema_editor):
    Employees = apps.get_model("employees", "Employees")
    VacationRequest = apps.get_model("leave", "VacationRequest")
    holiday_cache = {}

    def get_holiday_dates(start_date, end_date):
        cache_key = (start_date.year, end_date.year)
        if cache_key not in holiday_cache:
            holiday_cache[cache_key] = holidays.country_holidays("RU", years=range(start_date.year, end_date.year + 1))
        holiday_calendar = holiday_cache[cache_key]
        current_date = start_date
        dates = set()
        while current_date <= end_date:
            if current_date in holiday_calendar:
                dates.add(current_date)
            current_date += timedelta(days=1)
        return dates

    for employee in Employees.objects.all():
        used_up_days = 0
        approved_requests = VacationRequest.objects.filter(
            employee_id=employee.id,
            status="approved",
            vacation_type="paid",
        )
        for request_obj in approved_requests:
            chargeable_days = (request_obj.end_date - request_obj.start_date).days + 1
            chargeable_days -= len(get_holiday_dates(request_obj.start_date, request_obj.end_date))
            used_up_days += max(chargeable_days, 0)

        employee.annual_paid_leave_days = employee.annual_paid_leave_days or 52
        employee.vacation_days = employee.annual_paid_leave_days
        employee.used_up_days = max(used_up_days, 0)
        employee.save(update_fields=["annual_paid_leave_days", "vacation_days", "used_up_days"])


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_departments_options_alter_employees_options_and_more"),
        ("leave", "0003_alter_vacationrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="annual_paid_leave_days",
            field=models.PositiveIntegerField(
                default=52,
                validators=[django.core.validators.MaxValueValidator(52)],
                verbose_name="Годовая норма оплачиваемого отпуска",
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="manual_leave_adjustment_days",
            field=models.IntegerField(default=0, verbose_name="Ручная корректировка отпускного баланса"),
        ),
        migrations.AlterField(
            model_name="employees",
            name="used_up_days",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(3650)],
                verbose_name="Использованные дни",
            ),
        ),
        migrations.RunPython(recalculate_leave_balances, migrations.RunPython.noop),
    ]
