# Generated by Django 5.0.6 on 2026-04-23 12:36

import django.db.models.deletion
from django.db import migrations, models


def backfill_employee_roles(apps, schema_editor):
    Employees = apps.get_model("employees", "Employees")

    Employees.objects.filter(is_manager=True).update(role="enterprise_head")
    Employees.objects.filter(is_manager=False).update(role="employee")


def restore_legacy_manager_flag(apps, schema_editor):
    Employees = apps.get_model("employees", "Employees")

    Employees.objects.filter(role__in=["hr", "department_head", "enterprise_head"]).update(is_manager=True)
    Employees.objects.filter(role="employee").update(is_manager=False)


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employees_annual_paid_leave_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departments",
            name="head",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_department",
                to="employees.employees",
                verbose_name="Руководитель отдела",
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Сотрудник"),
                    ("hr", "HR"),
                    ("department_head", "Руководитель отдела"),
                    ("enterprise_head", "Руководитель предприятия"),
                ],
                default="employee",
                max_length=32,
                verbose_name="Роль в системе",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="employees.departments",
                verbose_name="Отдел",
            ),
        ),
        migrations.RunPython(backfill_employee_roles, restore_legacy_manager_flag),
    ]
