# Generated by Django 5.0.6 on 2026-04-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_departments_head_employees_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Сотрудник"),
                    ("hr", "HR"),
                    ("department_head", "Руководитель отдела"),
                    ("enterprise_head", "Руководитель предприятия"),
                    ("authorized_person", "Уполномоченное лицо"),
                ],
                default="employee",
                max_length=32,
                verbose_name="Роль в системе",
            ),
        ),
    ]
