# Generated by Django 5.0.6 on 2026-04-26 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_clean_authorized_person_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="is_working",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="password",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="used_up_days",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="vacation_days",
        ),
        migrations.AlterField(
            model_name="employees",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Дата начала работы"),
        ),
    ]
