# Generated by Django 5.0.6 on 2026-05-01 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employees_is_working_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='deputy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_department', to='employees.employees', verbose_name='Заместитель руководителя отдела'),
        ),
        migrations.AddField(
            model_name='employees',
            name='is_enterprise_deputy',
            field=models.BooleanField(default=False, verbose_name='Заместитель руководителя предприятия'),
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='employees.departments', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'employees_employeeposition',
                'ordering': ['department__name', 'production_group__name', 'title'],
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.employeeposition', verbose_name='Должность из справочника'),
        ),
        migrations.CreateModel(
            name='ProductionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Производственная группа')),
                ('code', models.CharField(blank=True, default='', max_length=80, verbose_name='Код группы')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_groups', to='employees.departments', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Производственная группа',
                'verbose_name_plural': 'Производственные группы',
                'db_table': 'employees_productiongroup',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='production_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='employees.productiongroup', verbose_name='Производственная группа'),
        ),
        migrations.CreateModel(
            name='DepartmentCoverageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_staff_required', models.PositiveSmallIntegerField(default=1, verbose_name='Минимум должно остаться')),
                ('max_absent', models.PositiveSmallIntegerField(default=1, verbose_name='Максимум отсутствующих')),
                ('criticality_level', models.PositiveSmallIntegerField(default=3, verbose_name='Критичность')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='employees.departments', verbose_name='Отдел')),
                ('production_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='employees.productiongroup', verbose_name='Производственная группа')),
            ],
            options={
                'verbose_name': 'Правило покрытия',
                'verbose_name_plural': 'Правила покрытия',
                'db_table': 'employees_departmentcoveragerule',
                'ordering': ['department__name', 'production_group__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionGroupSubstitutionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_rules', to='employees.departments', verbose_name='Отдел')),
                ('source_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_sources', to='employees.productiongroup', verbose_name='Кого замещают')),
                ('substitute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_targets', to='employees.productiongroup', verbose_name='Кто замещает')),
            ],
            options={
                'verbose_name': 'Правило замещения',
                'verbose_name_plural': 'Правила замещения',
                'db_table': 'employees_productiongroupsubstitutionrule',
                'ordering': ['department__name', 'source_group__name', 'substitute_group__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='productiongroup',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_production_group_name_per_department'),
        ),
        migrations.AddConstraint(
            model_name='employeeposition',
            constraint=models.UniqueConstraint(fields=('department', 'title'), name='unique_position_title_per_department'),
        ),
        migrations.AddConstraint(
            model_name='departmentcoveragerule',
            constraint=models.UniqueConstraint(fields=('department', 'production_group'), name='unique_coverage_rule_per_group'),
        ),
        migrations.AddConstraint(
            model_name='departmentcoveragerule',
            constraint=models.CheckConstraint(check=models.Q(('criticality_level__gte', 1), ('criticality_level__lte', 5)), name='coverage_rule_criticality_1_5'),
        ),
        migrations.AddConstraint(
            model_name='productiongroupsubstitutionrule',
            constraint=models.UniqueConstraint(fields=('department', 'source_group', 'substitute_group'), name='unique_production_group_substitution'),
        ),
    ]
